version: '3.1'

services:

  mongo:
    image: mongo:4.4.12
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081

volumes:
  db:                                                                                              
